service: c19-dashboard-api
useDotenv: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  profile: "${env:AWS_PROFILE}"
  role: "arn:aws:iam::${env:AWS_ID}:role/${env:AWS_ROLE}-${self:provider.stage}"
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: ${self:custom.logs.retention.${self:provider.stage}, 7}
  environment:
    ENV: ${self:provider.stage}
    REGION: ${self:provider.region}
    SERVICE_NAME: ${self:service}-${self:provider.stage}
    DYNAMO_URL: ${self:custom.dynamo.url.${self:provider.stage}, ""}
    DYNAMO_TABLE: ${self:custom.dynamo.table.cache}
    COVID_ACT_NOW_KEY: ${env:COVID_ACT_NOW_KEY}

custom:
  logs:
    retention:
      production: 14
      dev: 7
  webpack:
    webpackConfig: ./webpack.config.js
    packager: 'npm'
    includeModules:
      forceExclude:
        - dotenv 
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1
  prune:
    automatic: true
    number: 5
  domain:
    enabled:
      production: true
      dev: false
      local: false
  customDomain:
    domainName: c19.api.kolyaventuri.dev
    stage: production
    basePath: ''
    certificateName: 'kolyaventuri.dev'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    enabled: ${self:custom.domain.enabled.${self:provider.stage}}
  dynamo:
    table:
      cache: c19-dashboard-cache_${self:provider.stage}
    url:
      local: http://localhost:8000
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

functions:
  healthcheck:
    handler: src/healthcheck/get.handler
    description: Basic page ok healthcheck
    events:
      - http:
          path: v1/healthcheck
          method: get
  stateTimeseriesRisk:
    handler: src/states/risk/timeseries.handler
    description: State risk timeseries
    events:
      - http:
          path: v1/states/risk/timeseries
          method: get

resources:
  Resources:
    GeneratorTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamo.table.cache}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 3
    
plugins:
  - serverless-webpack
  - serverless-plugin-warmup
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-domain-manager
  - serverless-offline
  - serverless-dynamodb-local
